### ISSUE TITLE
Suspicious modules under `com.javax0`

### ISSUE THREAD

**Issue by Michael1993** [sormuras/modules#11]
Artifacts under javax0.com belong to [Peter Verhas](https://github.com/verhas).
If you can find it in their GitHub repository (e.g.: [jamal.core](https://github.com/verhas/jamal) or [geci.core](https://github.com/verhas/javageci)) then it is valid.

**Comment by Michael1993** [comment]
After scrolling a bit in [suspicious/naming.md](https://raw.githubusercontent.com/sormuras/modules/master/suspicious/naming.md), it seems fairly common to leave out the top-level domain from the beginning of your module name.
Maybe this case needs consideration? 🤔

**Comment by sormuras** [comment]
Thanks for the pointer, Michael.

> [...] leave out the top-level domain [...] Maybe this case needs consideration? 🤔

True. Although it would lead to (more) name clashes. Here's one example for such a pattern:

https://github.com/sormuras/modules/blob/4f23c27b21c3254f5c68f7043c76914e60f63fc8/maven-group-alias.properties#L8

If there are two or more `foo.bar` modules originating from:

- `com.foo.bar`
- `net.foo.bar`
- `org.foo.bar`
- `...`

Which one should be mapped? First come, first serve? Most "prominent" (Who decides? Me?) first? That's how I created the `maven-group-alias.properties` mapping in the first place. In cases of JavaFX, Kotlin, Spring, Scala, and some others, it was an easy and safe "guess". But I don't want to update/maintain that mapping for every contributor. That's why I really like this "rule":

> Module names must be reverse-DNS, just like package names, e.g. `org.joda.time`.

**Comment by sormuras** [comment]
> Artifacts under `javax0.com` belong to Peter Verhas.
> If you can find it in their GitHub repository (e.g.: jamal.core or geci.core) then it is valid.

That's not easy to guess nor easy to automate.

Mapping from the exact Maven GroupID `com.javax0.jamal` to the start of module names with `jamal` -- would work for most of Peter's Jamal modules. Except for the Maven ArtifactID `jamal-maven-plugin`, which drops the `plugin` part...

Same goes for `com.javax0.geci=geci`.

I'll extend `maven-group-alias.properties` mapping with both entries. Let's see how this works out.

PS: I guess, this pair might prevent the module to be indexed anyway.

- :dvd: `jamal.core` - `com.javax0.jamal:jamal-core:1.0.1`
- :dvd: `jamal.core` - `com.javax0.jamal:jamal-extensions:1.0.1`

**Comment by sormuras** [comment]
Looks better than expected. Nice.

https://github.com/sormuras/modules/commit/d5caab71e764c57c997822697caa72290b0b2f9a#diff-24354664c95afe49ef1d1595a8df6602
