### ISSUE TITLE
Top-level domain dropped from the beginning of module name

### ISSUE THREAD

**Issue by sormuras** [sormuras/modules#13]
After scrolling a bit in [suspicious/naming.md](https://raw.githubusercontent.com/sormuras/modules/master/suspicious/naming.md), it seems fairly common to leave out the top-level domain from the beginning of your module name.
Maybe this case needs consideration? 🤔

_Originally posted by @Michael1993 in https://github.com/sormuras/modules/issues/11#issuecomment-688220351_

**Comment by Michael1993** [comment]
As far as I know, if you upload an artifact (e.g.: `org.foo.bar:bartifact:1.0.0`) to maven central it is a prerequisite that you own the domain `foo.org`.
I'm mentioning this because this should be a safeguard from _impostor modules_?

My best guess right now would be a "first-come-first-serve" model. If there is no competition for a particular module name, (e.g.: there is no `org.foo.bar` and `com.foo.bar`, only `net.foo.bar`) then is there a reason not to be optimistic about them and "let them in"?

**Comment by sormuras** [comment]
I like module names best when they start with a TLD.

Common (well-known) exceptions to that rule are already covered by [maven-group-alias.properties](https://github.com/sormuras/modules/blob/master/maven-group-alias.properties)

Extending this hand-crafted mapping is a good enough solution for the time being.

**Comment by lingocoder** [comment]
> „*I like module names best when they start with a TLD…*“

That seems capriciously restrictive. The majority of [*the JDK's module names*](https://docs.oracle.com/en/java/javase/15/docs/api/) don't even meet your criteria…

>> * *Module names must be reverse-DNS, just like package names, e.g. org.joda.time.*
>> * *Modules are a group of packages. As such, the module name must be related to the package names.*
>> * *Module names are strongly recommended to be the same as the name of the super-package.*

**Comment by sormuras** [comment]
> That seems capriciously restrictive.

No.

> The majority of the JDK's module names don't even meet your criteria…

Yes. And...?

**Comment by sormuras** [comment]
Feel free to upvote https://github.com/sonatype-nexus-community/search-maven-org/issues/6 and https://youtrack.jetbrains.com/issue/PKGS-451 -- would be nice to have those indexes updated in 2020. All kind of module names (even invalid ones) are allowed there.

This project will stick with strict(er) naming conventions.

**Comment by lingocoder** [comment]
>> *The majority of the JDK's module names don't even meet your criteria…*
> 
> *Yes. And...?*

And…given a choice between the advice from a rando on github and that of [*the stewards of the language*](https://mail.openjdk.java.net/pipermail/jpms-spec-experts/2017-February/000582.html)…

>> *- Module names should use the reverse-domain-name-prefix convention
    or, **preferably, the project-name-prefix convention**.*
>> …
>> *The reversed domain-name approach was sensible in the early days of Java,
before we had development tools sophisticated enough to help us deal with
the occasional conflict.  We have such tools now, **so going forward the
superior readability of short module and package names that start with
project or product names is preferable to the onerous verbosity of those
that start with reversed domain names**.*

…I'll stick with the language steward's preference instead of your personal preference.

And…your personal preference means nothing to the majority of the project maintainers who will give up in frustration after trying to decipher the meaning of the data in your inadequately labeled lists.
