### ISSUE TITLE
Clarify what the data fields and terminology mean

### ISSUE THREAD

**Issue by lingocoder** [sormuras/modules#14]
In the absence of any headers or anything to identify what the different fields are, it is not clear what an entry like this one from [*naming.md*](https://github.com/sormuras/modules/blob/master/suspicious/naming.md) means…

>> - :cd: `java.xml.bind` - `org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec:2.0.0.Final` // `org.jboss.spec.javax.xml.bind,jboss-jaxb-api_2.3_spec,2.0.0.Final,java.xml.bind,-,automatic,-,true,-`

Nor examples like this one from [*imposters.md*](https://github.com/sormuras/modules/blob/master/suspicious/impostors.md)…

>> - :dvd: `com.jwebmp.plugins.moment` - `com.jwebmp.plugins.javascript:jwebmp-momentjs:1.0.2.8` // `com.jwebmp.plugins.javascript,jwebmp-momentjs,1.0.2.8,com.jwebmp.plugins.moment,1.0.2.8,explicit,com.fasterxml.jackson.annotation + com.guicedee.guicedinjection + com.guicedee.logmaster + com.jwebmp.core + com.jwebmp.core.angularjs + java.base + java.logging + java.validation,false,-`

What are „*`:cd:`*“  and „*`:dvd:`*“ supposed to indicate? VS Code's markdown viewer doesn't recognize them as anything other than the literal strings…

![wtf is cd and dvd](https://user-images.githubusercontent.com/49788472/97120589-112cdb00-1710-11eb-9a1c-5f4ae62747d0.png)

 In my browser, they render as something broken…

![wtf is dvd and cd](https://user-images.githubusercontent.com/49788472/97120683-c2337580-1710-11eb-8460-e3f7990b63d7.png)

It is also not clear what „*imposter*“ means. Please clarify?

**Comment by sormuras** [comment]
Hi.

> This project applies that strategy to compile a database of **unique** module names derived from artifacts published on Maven Central.

Good starting points are:
- https://blog.joda.org/2017/04/java-se-9-jpms-module-naming.html
- https://mail.openjdk.java.net/pipermail/jpms-spec-experts/2017-February/000582.html

Your concrete examples:

- ![image](https://user-images.githubusercontent.com/2319838/97132590-badb8e80-1747-11eb-84d3-4e0ac9782cea.png)

GroupId doesn't start with `java.xml.bind`: not part of this database

- ![image](https://user-images.githubusercontent.com/2319838/97133062-06db0300-1749-11eb-8b6f-1226f6210efd.png)

There's an explicit module that already took the ownership of `com.jwebmp.plugins.moment`. Mapping to `com.jwebmp:jwebmp-momentjs`:

![image](https://user-images.githubusercontent.com/2319838/97133307-e65f7880-1749-11eb-8582-c5244d0cecd7.png)

That's why all later uploads using the same module name with different GA are considered impostors.

![image](https://user-images.githubusercontent.com/2319838/97133409-49e9a600-174a-11eb-973b-684e08ac99e9.png)

- 
![image](https://user-images.githubusercontent.com/2319838/97133448-6259c080-174a-11eb-956e-23c44b3192d9.png)

> 💿 is "an automatic module", i.e. it declares a stable module name via an `AUTOMATIC-MODULE-NAME` entry in its `META-INF/MANIFEST.MF` file.
> 📀 denotes an explicit containing a compiled `module-info.class` module descriptor.

Regarding VS Code and your browser: well...

The term "impostor" is explained above.

HTH.

**Comment by lingocoder** [comment]
> *Regarding VS Code and your browser: well...*

Regarding thousands of project maintainers changing their artifact names just because ***you*** love making lists of poorly explained data; well…Don't hold your breath.

**Comment by lingocoder** [comment]
> *The term "impostor" is explained above.*
>
> *HTH.*

That was helpful; to me individually. Thanks, But the intent of raising this issue was not for you to be helpful to me individually. The intent of raising this issue is to hopefully get clarification amended to this repo's [*READMEs*](https://github.com/sormuras/modules/blob/master/README_ABOUT.md); for the sake of the thousands of other project maintainers in your database.

> *Good starting points are:*
> * &nbsp;
> * &nbsp;

Isn't the process of modularizing a project laborious enough? 

Why not make the process at least somewhat easier by sparing project maintainers the necessity of trawling through four different pages of documentation just to understand your lists?

> *There's an explicit module that already took the ownership of `com.jwebmp.plugins.moment`. Mapping to `com.jwebmp:jwebmp-momentjs`*:

I know this might sound snarky. But I'm not trying to be; honest. This is an actual, innocent question that I'm genuinely curious to understand… 

* *Do you think that's obvious just going by what you've written in your READMEs*?

**Comment by Michael1993** [comment]
> The intent of raising this issue is to hopefully get clarification amended to this repo's READMEs; for the sake of the thousands of other project maintainers in your database.

If you believe the README could be improved feel free to open a PR. Personally, I found the README intuitive but that's anecdotal - I'm certain it could be better.

> Isn't the process of modularizing a project laborious enough?

I'm not sure if this was a rhetorical question so I'm going to address this. I've modularized large and small legacy projects as well as writing several modular Java projects for fun. TL;DR: The larger the project, the harder it is.

Longer version: In my experience modularizing a project is fairly straightforward. There are excellent resources available to learn about modules and modern IDEs have built-in support for them. Whenever I had problems with modularization, it always seemed to boil down to architectural problems: layers not properly separated, high coupling/low cohesion, etc. Of course, no project is perfect, so modularizing often can be simplified to the TL;DR: the larger the project, the harder it is. I think the same can be said for all retroactive architectural changes.

If you start an application from scratch it's only a minor adjustment to incorporate modules into your architecture. Again, speaking only from my personal experience.

> Why not make the process at least somewhat easier by sparing project maintainers the necessity of trawling through four different pages of documentation just to understand your lists?

Maybe it's because I'm young and inexperienced but I don't think that's a lot? I think I read more documentation today just to remind me to add `basePackages = "com.example.project"` to my `@SpringBootApplication` annotation... 😅 
Then again, the less we have to spend reading documentation, the better, so if you think you can improve the `README` feel free to open a PR.

> Do you think that's obvious just going by what you've written in your READMEs?

For me it's obvious from the name itself: there are _normal modules_ (which are just _modules_, I think) and there are _impostor modules_.
An impostor is:
> a person who pretends to be someone else in order to deceive others, especially for fraudulent gain.

From this, it seems logical that _impostor modules_ are modules pretending to be _normal modules_ where the normal module already exists.

**Comment by lingocoder** [comment]
> *feel free to open a PR*

And waste more of my time? Nah! I'm good. Thanks.

Your README requests: „[*If you find your module listed there, or know an author of one, please create an issue for investigation*](https://github.com/sormuras/modules#suspicious-modules-found-on-maven-central)“. If you ever wonder why after two years, this project has so few responses (*what, three in total?*) to that call to action, reread your and @sormuras above comments.

**Comment by sormuras** [comment]
Fixed.

> And waste more of our time?

Fair winds and following seas.

**Comment by lingocoder** [comment]
> *Fixed.*
>
>> *And waste more of our time?*

You're wasting your own time, bruh. LOL! In two years you've had a whopping total of three responses to your „[*please create an issue for investigation*](https://github.com/sormuras/modules#suspicious-modules-found-on-maven-central)“. 

[*The first*](https://github.com/sormuras/modules/issues/2) and [*the second*](https://github.com/sormuras/modules/issues/3) ones from the same one guy. Then [*the third*](https://github.com/sormuras/modules/issues/11) one from your best bud @Michael1993.

When will you get the hint? [*Nobody cares about your personal preferences*](https://github.com/sormuras/modules/issues/13#issuecomment-716592907); except you. LOL!
